env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
parser: "vue-eslint-parser"
parserOptions:
  parser: "@typescript-eslint/parser"
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent: ["error", 2]
  linebreak-style: ["error", "unix"]
  quotes: ["error", "double"]
  semi: ["error", "never"]
  arrow-parens: ["error", "as-needed"]
  arrow-spacing: error
  comma-dangle: ["error", "never"]
  space-in-parens: ["error", "never"]
  array-bracket-spacing: ["error", "never"]
  no-trailing-spaces: "error"
  space-before-function-paren:
    - error
    - anonymous: always
      named: never
      asyncArrow: always
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_
      caughtErrorsIgnorePattern: ^_
  vue/max-attributes-per-line:
    - error
    - singleline: 99
      multiline: 1
